# Generated by Django 5.1.5 on 2025-02-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_order.purchaseorder'),
        ),
    ]
