# Generated by Django 5.1.5 on 2025-02-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='LowStockAlert',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
