# Generated by Django 5.1.5 on 2025-03-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_alter_product_cost_price_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
