# Generated by Django 5.1.5 on 2025-02-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
    ]
